# final-project

## Grading: out of 68 points
## Score: 57 (A range)


#### Stat content: (0-8 scale): 18

- Graphics: 6
  - map popups: include a label and round your number (it takes a little html work but it can be done by copying examples shown on the leaflet help page)
  - edit the axes labels and titles on your graphs to make them more informative
  
- Tables/Stats: 6
  - a stat like number of killings in a community should be standardized so city size isn't a confounding variable

- Methods: 6
  - prediction: explain more about the variables used, why include the 3 variables for prediction and not include others? (e.g. police force prop is low in importance, so why included it as a factor?)


#### Communication: (0-8 scale): 12

- Data: 6
  - more about your variables would be useful, e.g how are hate crimes determined?
  
- Takeaways: 6


#### Website: (0-4 scale): 4

- Layout: 4


#### Scope/Creativitiy: (0-4 scale): 7

- Scope:  4
- Creativity:  3


#### Technical (0-4 scale): 16

- coding style: 4
- coding strategy: 4
- access: 4
- report: 4


---------------------------------------


**Statistical content** (8 point scale)

Topic| Excellent: 8 | Satisfactory: 4 | Inadequate: 0 |
|----| ------ |-------| -----|
| **Graphics** | Graph(s) carefully tuned for desired purpose. One graph illustrates one point. Table(s) carefully constructed to make it easy to perform important comparisons. Careful styling highlights important features. | Graph(s) well chosen, but with a few minor problems: inappropriate aspect ratios, poor labels. Table(s) generally appropriate but possibly some minor formatting deficiencies. | Graph(s) poorly chosen to support questions. Table(s) with too many, or inconsistent, decimal places. Table(s) not appropriate for questions and findings. Major display problems. |
|**Tables/Stats** | Table(s)/Stats provided and carefully constructed to make it easy to perform important comparisons. Careful styling highlights important features. |  Table(s)/Stats  generally appropriate but possibly some minor formatting deficiencies. | Table(s)/Stats  with too many, or inconsistent, decimal places. Table(s) not appropriate for questions and findings. Major display problems. |
|**Methods** | Appropriate methods used (e.g. wrangling, modeling, etc) |  Methods used are mostly well chosen, but contain some minor problems. | Methods used are inappropriate |

**Communication** (8 point scale)

Topic| Excellent: 8 | Satisfactory: 4 | Inadequate: 0 |
|----| ------ |-------| -----|
| **Data**     | Website contains enough written information to clearly and engagingly describe the data, data sources, and why it is of interest.  | Data are explained but certain aspects lack clarity. | Data are not completely or correctly explained.|
| **Takeaways**     | Website contains enough written information to clearly and engagingly describe the major takeaways that the viewer should be able to gain from results presented.  | Results are explained but certain aspects lack clarity. | Results are not completely or correctly explained.|


**Website** (4 point scale)

Topic| Excellent: 4 | Satisfactory: 2 | Inadequate: 0 |
|----| ------ |-------| -----|
| **Layout** | Website is visually appealing, engaging and easy to navigate.  | Website works but is not particularly engaging or  visually appealing.  | Website does not function or has major navigating issues.|


**Scope and creativity** (4 point scale)

Topic| Excellent: 4 | Satisfactory: 2 | Inadequate: 0 |
|----| ------ |-------| -----|
|**Scope** Achievement, mastery |Group has gone beyond what was expected and required in terms of scope, e.g., extraordinary effort, additional tools not addressed by this course.| Tools and techniques from the course are applied very competently. Chosen task was acceptable, but fairly conservative in ambition.|Group does not display the expected level of mastery of the tools and techniques in this course. Chosen task was too limited in scope.|
|**Creativity** Cleverness, creativity| Group has gone beyond what was expected and required in terms of creativity, e.g. unusually sophisticated and creative use of tools from course.| Tools and techniques from the course are applied somewhat creatively. | Group does not display any creative use of the tools and techniques in this course. |



**Technical aspects** (4 point scale)

Topic| Excellent: 4 | Satisfactory: 2 | Inadequate: 0 |
|----| ------ |-------| -----|
|Coding **style**| Coding style is followed (e.g. avoids run on "sentences" of code), code is well commented | Coding style lacks refinement and has some errors, but code is readable and has some comments | Many errors in coding style, little attention paid to making the code human readable|
|Coding **strategy**| Complicated problem broken down into sub-problems that are individually much simpler. Code is efficient, correct, and minimal. Code checks for common errors  | Code is correct, but could be edited down to simplier code chunks. Some checks for errors. |   Code tackles complicated problem in one big chunk. Code is repetitive and could easily be functionalized. No anticipation of errors. |
|Ease of **access**, compliance with course conventions for submitted work|Access as easy as possible, code runs! | Satisfactory | Not an earnest effort to reduce friction and comply with conventions  and/or code does not run|
| Technical **report**     | Report is complete, contains all major steps  | Methods are explained but certain aspects lack clarity. | Methods are not explained.|
